var res = {
    home_jpg : "res/home.jpg",
    homeScene : "res/MainScene.json",
    homeBackgroundLayer : "res/homeBackgroundLayer.json",
    homeButtonLayer : "res/homeButtonLayer.json",
    scoreboardLayer : "res/ScoreboardLayer.json",
    scoreboardScene : "res/ScoreboardScene.json",
    playerNameLayer : "res/playerNameLayer.json",
    playerNameScene : "res/playerNameScene.json",
    operationLayer : "res/operationLayer.json",
    operationScene : "res/operationScene.json",
    difficultyScene : "res/DifficultyScene.json",
    difficultyLayer : "res/difficultyLayer.json",
    instructionLayer : "res/layerInstruction.json",
    firstLayer : "res/firstLayer.json",
    backgroundPlayLayer: "res/layerBackgroundPlay.json",
    playMusic : "res/media/sounds/bitOfFun.mp3",
    playSwallow : "res/media/sounds/swallowing.mp3",
    homeSprite : "res/nodeOptions.json",
    menuLayer: "res/MenuLayer.json",
    fairySpriteSheet : "res/media/graphics/sprites.png",
    fairySpriteSheetXML : "res/media/graphics/fairySpritesheet.xml",
    fairySpriteSheetPLIST : "res/media/graphics/sprites.plist",
    fairy : "res/media/graphics/fairy",
    scene : "res/Scene.json",
    answerSpritesPLIST : "res/media/graphics/answerSprites.plist",
    levelLayer : "res/LevelLayer.json",
    articulaFont : "res/media/Fonts/ArticulaDisplaySSI.ttf",
    deannaFont : "res/media/Fonts/Deanna.ttf",
    impactFont : "res/media/Fonts/impact.ttf",
    strangeWorldFont : "res/media/Fonts/StrangeWorld.ttf",
    easyModeComplete : "res/easyModeComplete.json",
    advancedModeComplete : "res/advancedModeComplete.json",
    difficultModeComplete : "res/difficultModeComplete.json",
    redSprite : "res/media/graphics/red.png",
    yellowSprite : "res/media/graphics/yellow.png",
    pinkSprite : "res/media/graphics/pink.png",
    lightGreenSprite : "res/media/graphics/lightGreen.png",
    lightPurpleSprite : "res/media/graphics/lightPurple.png",
    lightGreenSprite : "res/media/graphics/lightGreen.png",
    blackSprite : "res/media/graphics/black.png",
    royalBlueSprite : "res/media/graphics/royalBlue.png",
    darkBlueSprite : "res/media/graphics/darkBlue.png",
    brownSprite : "res/media/graphics/brown.png",
    correctSprite : "res/media/graphics/correct.png",
    wrongSprite : "res/media/scoreboard/wrong.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
